site_name: repo prueba
site_description: descripcion prueba
site_author: Devopsross
site_url: https://blog.devops.com
repo_url: https://github.com/Devopsross/web-nodejs-basic
edit_uri: edit/main/docs
plugins: 
  - techdocs-core
nav:
  - Home: index.md
  - Management: managing.md   
